// layout.js
import { Inter } from 'next/font/google';
import './globals.css';
import Link from 'next/link';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav>
          <h1>NAVEGACIÓN</h1>
          <ul>
            <li>
              <Link href="/">Inicio</Link>
            </li>
            <li>
              <Link href="/dashboard">Acerca de "Tus Libros a un Click</Link>
            </li>
          </ul>
        </nav>
        <br />
        {children}
      </body>
    </html>
  );
}
